version: "3"

services:
  app:
    container_name: vinnfun
    image: vinnfun
    build:
      context: .
      dockerfile: Dockerfile
    user: "node"
    environment:
      - TZ=Europe/Budapest
    restart: unless-stopped
    ports:
      - 3000:3000
